a = input('digite alguma coisa ai')
print(f'É numérico?',a.isnumeric())
print(f'Tem espaços?',a.isspace())
print(f'É alfabético?',a.isalpha())
print(f'É um alfanumérico?',a.isalnum())
print(f'Está em letras maiúsculas?',a.isupper())
print(f'Está em letras minúsculas?',a.islower())
print('Só tem espaços?', a.isspace())
print('Está capitalizada?', a.istitle())
